# Generated by Django 4.0.4 on 2022-04-28 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinname',
            options={'ordering': ('-created_data',)},
        ),
        migrations.AddField(
            model_name='coinname',
            name='created_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
